export interface Verse {
  text: string;
  reference: string;
}

export const BIBLIA_CURADA: Verse[] = [
  { text: "No princípio, criou Deus os céus e a terra.", reference: "Gênesis 1:1" },
  { text: "O Senhor é o meu pastor; nada me faltará.", reference: "Salmos 23:1" },
  { text: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito.", reference: "João 3:16" },
  { text: "Eu sou o Alfa e o Ômega, o Princípio e o Fim, diz o Senhor.", reference: "Apocalipse 1:8" },
  { text: "Tudo posso naquele que me fortalece.", reference: "Filipenses 4:13" },
  { text: "O temor do Senhor é o princípio da sabedoria.", reference: "Provérbios 1:7" },
  { text: "Consagra ao Senhor as tuas obras, e teus pensamentos serão estabelecidos.", reference: "Provérbios 16:3" },
  { text: "Eis que faço novas todas as coisas.", reference: "Apocalipse 21:5" },
  { text: "Sê forte e corajoso; não temas, nem te espantes.", reference: "Josué 1:9" },
  { text: "A graça do Senhor Jesus seja com todos. Amém.", reference: "Apocalipse 22:21" },
  { text: "Lâmpada para os meus pés é tua palavra e luz, para o meu caminho.", reference: "Salmos 119:105" },
  { text: "Buscai primeiro o Reino de Deus e a sua justiça.", reference: "Mateus 6:33" },
  { text: "O Senhor te abençoe e te guarde.", reference: "Números 6:24" },
  { text: "Alegrei-me quando me disseram: Vamos à Casa do Senhor.", reference: "Salmos 122:1" },
  { text: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.", reference: "Salmos 46:1" },
  { text: "O coração alegre aformoseia o rosto.", reference: "Provérbios 15:13" },
  { text: "Em tudo dai graças, porque esta é a vontade de Deus.", reference: "1 Tessalonicenses 5:18" },
  { text: "O Senhor é a minha luz e a minha salvação; a quem temerei?", reference: "Salmos 27:1" },
  { text: "Grandes coisas fez o Senhor por nós, e por isso estamos alegres.", reference: "Salmos 126:3" },
  { text: "Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum.", reference: "Salmos 23:4" },
  { text: "A palavra de Cristo habite em vós abundantemente.", reference: "Colossenses 3:16" },
  { text: "Cantai ao Senhor um cântico novo, cantai ao Senhor, todas as terras.", reference: "Salmos 96:1" },
  { text: "Servi ao Senhor com alegria e apresentai-vos a ele com canto.", reference: "Salmos 100:2" },
  { text: "Louvai ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre.", reference: "Salmos 136:1" },
  { text: "Pois onde estiverem dois ou três reunidos em meu nome, ali estou eu.", reference: "Mateus 18:20" },
  { text: "Cantai-lhe um cântico novo; tocai bem e com júbilo.", reference: "Salmos 33:3" },
  { text: "Deus é Espírito, e importa que os que o adoram o adorem em espírito e em verdade.", reference: "João 4:24" },
  { text: "Louvai ao Senhor. Louvai a Deus no seu santuário; louvai-o no firmamento do seu poder.", reference: "Salmos 150:1" },
  { text: "Tudo quanto tem fôlego louve ao Senhor. Louvai ao Senhor.", reference: "Salmos 150:6" },
  { text: "O Senhor é a minha força e o meu escudo; nele confiou o meu coração, e fui socorrido.", reference: "Salmos 28:7" },
  { text: "Entrai pelas portas dele com gratidão, e em seus átrios com louvor.", reference: "Salmos 100:4" },
  { text: "Ofereçamos sempre por ele a Deus sacrifício de louvor.", reference: "Hebreus 13:15" },
  { text: "E, quando começaram a cantar e a dar louvores, o Senhor pôs emboscadas.", reference: "2 Crônicas 20:22" },
  { text: "Bom é louvar ao Senhor, e cantar louvores ao teu nome, ó Altíssimo.", reference: "Salmos 92:1" },
];

export const REFLECTIONS = [
  { text: "A adoração não é sobre o quão bem tocamos, mas sobre para Quem tocamos.", author: "Mestre de Música" },
  { text: "O ensaio é o momento de errar; o culto é o momento de se entregar.", author: "Ministro de Louvor" },
  { text: "Mantenha seu instrumento afinado, mas sua alma ainda mais.", author: "Teólogo Musical" },
  { text: "A simplicidade muitas vezes comunica mais do que o virtuosismo.", author: "Arranjador" },
  { text: "Louvor é a Palavra de Deus cantada. Seja fiel às Escrituras.", author: "Firmados em Cristo" },
  { text: "Seu talento pode te levar ao altar, mas só a santidade te mantém lá.", author: "Ministro de Louvor" },
  { text: "Deus não procura grandes músicos, Ele procura verdadeiros adoradores.", author: "Teólogo Musical" },
  { text: "A música é o veículo, mas a mensagem é a cruz.", author: "Firmados em Cristo" },
  { text: "Antes de abrir o instrumento, abra o coração em oração.", author: "Mestre de Música" },
  { text: "O brilho do músico nunca deve ofuscar a glória de Deus.", author: "Arranjador" },
  { text: "Adorar é um estilo de vida, não um evento de domingo.", author: "Ministro de Louvor" },
  { text: "A técnica sem unção é apenas barulho; a unção sem técnica é desleixo.", author: "Mestre de Música" },
  { text: "Seja o primeiro a ser ministrado pela canção que você vai tocar.", author: "Teólogo Musical" },
  { text: "O maior solo que você pode fazer é o da rendição total.", author: "Arranjador" },
  { text: "Nossa meta é que as pessoas saiam do culto falando de Jesus, não da banda.", author: "Firmados em Cristo" },
  { text: "A excelência honra a Deus e inspira as pessoas.", author: "Mestre de Música" },
  { text: "O louvor prepara o solo do coração para a semente da Palavra.", author: "Ministro de Louvor" },
  { text: "Não toque para ser visto, toque para que Ele seja visto.", author: "Teólogo Musical" },
  { text: "A harmonia da banda começa na harmonia entre os irmãos.", author: "Arranjador" },
  { text: "O melhor arranjo é aquele que serve à congregação.", author: "Firmados em Cristo" },
  { text: "Sua vida fora do altar valida seu ministério sobre ele.", author: "Ministro de Louvor" },
  { text: "A música é uma linguagem que Deus nos deu para falar com Ele.", author: "Mestre de Música" },
  { text: "O ensaio técnico é necessário, mas a preparação espiritual é vital.", author: "Teólogo Musical" },
  { text: "Seja um canal, não um reservatório da glória de Deus.", author: "Arranjador" },
  { text: "O louvor é a arma que derruba as muralhas do desânimo.", author: "Firmados em Cristo" },
  { text: "A adoração é o transbordar de um coração que se encontrou com o Criador.", author: "Ministro de Louvor" },
  { text: "Não cante apenas com a voz, cante com a vida.", author: "Teólogo Musical" },
  { text: "O silêncio diante de Deus é, muitas vezes, a mais profunda adoração.", author: "Mestre de Música" },
  { text: "A música passa, mas a Palavra permanece para sempre.", author: "Firmados em Cristo" },
];

export const MUSICAL_TIPS = [
  { title: "Dinâmica", text: "Nem tudo precisa ser forte o tempo todo. Aprecie o piano e o forte." },
  { title: "Escuta Ativa", text: "Ouça os outros instrumentos. O louvor é um corpo unido, não um solo." },
  { title: "O Silêncio", text: "O silêncio também é música. Saiba quando não tocar para dar espaço à voz." },
  { title: "Preparação", text: "Estude seu instrumento em casa para que no ensaio possamos unir os corações." },
  { title: "Vocal: Respiração", text: "Respire pelo diafragma para sustentar as notas sem forçar as cordas vocais." },
  { title: "Vocal: Unidade", text: "No backing vocal, tente 'colar' sua voz na do líder. Não tente se destacar." },
  { title: "Violão/Guitarra", text: "Menos é mais. Deixe espaço para o teclado e não embole as frequências médias." },
  { title: "Baixo: O Alicerce", text: "Sua função é unir a harmonia ao ritmo. Seja preciso e constante com o bumbo." },
  { title: "Bateria: Intensidade", text: "Controle sua força. A bateria deve conduzir a energia, não ensurdecer a igreja." },
  { title: "Teclado: Texturas", text: "Use pads para preencher os vazios e pianos para marcar a harmonia com clareza." },
  { title: "Vocal: Dicção", text: "Pronuncie bem as palavras. A igreja precisa entender a mensagem que está sendo cantada." },
  { title: "Guitarra: Timbre", text: "Busque um timbre que se encaixe no mix da banda, sem excesso de distorção." },
  { title: "Ritmo: Metrônomo", text: "Pratique com metrônomo. A firmeza rítmica traz segurança para toda a igreja cantar." },
  { title: "Vocal: Expressão", text: "Cante com verdade. Sua expressão facial deve refletir a alegria ou a reverência da letra." },
  { title: "Instrumental: Espaço", text: "Saiba quando parar. Às vezes, o melhor arranjo é aquele onde você não toca." },
  { title: "Afinação", text: "Sempre confira a afinação antes do culto. Instrumentos desafinados distraem a igreja." },
  { title: "Vocal: Aquecimento", text: "Faça exercícios vocais antes de cantar para evitar lesões e melhorar o timbre." },
  { title: "Guitarra: Delay", text: "Use o delay no tempo da música (Tap Tempo) para criar texturas atmosféricas." },
  { title: "Teclado: Sustain", text: "Cuidado com o pedal de sustain. Não deixe as notas embolarem demais." },
  { title: "Bateria: Viradas", text: "Faça viradas que sirvam à transição da música, sem perder o tempo." },
  { title: "Vocal: Microfone", text: "Aprenda a distância correta do microfone para controlar o volume da sua voz." },
  { title: "Baixo: Groove", text: "Mantenha o groove simples e sólido. Você é o coração rítmico da banda." },
  { title: "Violão: Palhetada", text: "Varie a intensidade da palhetada de acordo com a dinâmica da música." },
  { title: "Instrumental: Solo", text: "Se houver um solo, que ele seja melódico e aponte para a mensagem da canção." },
  { title: "Vocal: Harmonia", text: "Estude as terças e quintas para criar aberturas vocais ricas e afinadas." },
  { title: "Comunicação Visual", text: "Mantenha contato visual com a banda e com a igreja. Isso gera conexão." },
  { title: "Transições", text: "Pense em como uma música termina e a outra começa. Transições suaves ajudam no fluir do culto." },
];
